version: "3"
services:
  app:
    build:
      context: ./.docker
      dockerfile: php/Dockerfile
      args:
        PHP_VERSION: fpm
    tty: true
    environment:
      XDEBUG_MODE: debug,coverage
      XDEBUG_SESSION_START: 1
      XDEBUG_CONFIG: client_host=localhost client_port=9003 discover_client_host=true start_on_request=yes
    networks:
      - internal
    volumes:
      - .:/var/www/html
    user: ${UID}:${GID}
    ports:
      - 8000:8000
    command: php -S 0.0.0.0:8000 -t public/
  composer:
    image: composer
    volumes:
      - .:/app
    user: ${UID}:${GID}
    depends_on:
      - app
    command: composer install

networks:
  internal:
    driver: bridge
