version: "3"
services:
  nginx:
    build:
      context: ./.docker
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
    user: ${UID}:${GID}
  app:
    build:
      context: ./.docker
      dockerfile: php/Dockerfile
      args:
        PHP_VERSION: fpm
    tty: true
    environment:
      XDEBUG_MODE: debug,coverage
      XDEBUG_SESSION_START: 1
      XDEBUG_CONFIG: client_host=localhost client_port=9003 discover_client_host=true start_on_request=yes
    networks:
      - internal
    volumes:
      - .:/var/www/html
    user: ${UID}:${GID}
  composer:
    image: composer
    volumes:
      - .:/app
    user: ${UID}:${GID}
    depends_on:
      - app
    command: composer install

networks:
  internal:
    driver: bridge
